Fix kubectl_follow_logs_until_file_appears function and add kubectl_follow_logs

diff --git a/base.yaml b/base.yaml
--- a/base.yaml
+++ b/base.yaml
@@ -104,38 +104,37 @@ functions:
     done
   # Follow pod logs, until the pod finishes
   # $POD_NAME - name of the pod to print logs for
-  # $CONTAINER - name of the container to print logs for
   # $TIMEOUT - (optional) (default: 60) timeout in seconds
   # $REF_COMMAND - (optional) Name of the referring command. This will be printed in the logs.
   kubectl_follow_logs: |-
     POD_NAME="$1"
-    CONTAINER="$2"
-    [[ -n $3 ]] && TIMEOUT=$3 || TIMEOUT=60
-    [[ -n $4 ]] && REF_COMMAND="$4" || REF_COMMAND=""
+    [[ -n $2 ]] && TIMEOUT=$2 || TIMEOUT=60
+    [[ -n $3 ]] && REF_COMMAND="$3" || REF_COMMAND=""
     [[ -n $REF_COMMAND ]] && THIS_COMMAND_PREFIX="$REF_COMMAND > " || THIS_COMMAND_PREFIX=""
     THIS_COMMAND="${THIS_COMMAND_PREFIX}kubectl_follow_logs_until_starting"
     echo ">> $THIS_COMMAND: Running kubectl_follow_logs_until_starting() $@"
-    # Validate pod name
-    require_vars POD_NAME CONTAINER
     # Follow logs in the background
     # Start the time
     START_TIME=$(date +%s)
-    # Wait until the container is created (otherwise logs will not be available)
-    while true; do
-      # If no longer waiting, break
-      if [[ -z "$(kubectl get --namespace=${APP_NAME} pod/$POD_NAME -o jsonpath='{.status.containerStatuses[?(@.name=="'$CONTAINER'")].state.waiting}')" ]]; then
-        echo ">> $THIS_COMMAND: Container $CONTAINER is available.."
-        break
-      else
-        sleep 1
-        kubectl get --namespace=${APP_NAME} pod/$POD_NAME -o jsonpath='{.status.containerStatuses[?(@.name=="'$CONTAINER'")].state.waiting}'
-        now=$(date +%s)
-        if [ $(($now - $START_TIME)) -gt $TIMEOUT ]; then
-          echo ">> $THIS_COMMAND: Error! Timeout waiting for container $CONTAINER to start."
-          exit 1
+    # If the pod hasn't been created, wait until it's created (otherwise logs will not be available)
+    if [[ "$(kubectl get --namespace=${APP_NAME} pod/$POD_NAME -o jsonpath='{.status.phase}')" != "Pending" ]]; then
+      echo ">> $THIS_COMMAND: Waiting for pod/$POD_NAME to be created."
+      while true; do
+        POD_STATUS="$(kubectl get --namespace=${APP_NAME} pod/$POD_NAME -o jsonpath='{.status.phase}')"
+        # If pod is not in pending state, break
+        if [[ "$POD_STATUS" != "Pending" ]]; then
+          echo ">> $THIS_COMMAND: The pod has been created."
+          break
+        else
+          sleep 1
+          now=$(date +%s)
+          if [ $(($now - $START_TIME)) -gt $TIMEOUT ]; then
+            echo ">> $THIS_COMMAND: Error! Timeout waiting for pod/$POD_NAME to be created."
+            exit 1
+          fi
         fi
-      fi
-    done
+      done
+    fi
     # Follow logs
     echo ">> $THIS_COMMAND: Following logs for pod/$POD_NAME --all-containers=true"
     kubectl logs --namespace=${APP_NAME} --all-containers=true $POD_NAME --follow &
@@ -167,10 +166,11 @@ functions:
       echo ">> $THIS_COMMAND: Killing PID $PID"
       kill $PID || true
     done
-  # Follow pod logs, until the specified file appears
+  # Follow pod logs, until the specified file appears. The caveat is that the logs cannot start until the specified
+  # container gets created.
   # $FILE_PATH - absolute path of the file to wait for
   # $POD_NAME - name of the pod to print logs for
-  # $CONTAINER - name of the container to print logs for
+  # $CONTAINER - name of the container which holds the file
   # $TIMEOUT - (optional) (default: 60) timeout in seconds
   # $REF_COMMAND - (optional) Name of the referring command. This will be printed in the logs.
   kubectl_follow_logs_until_file_appears: |-
