Fix kubectl_follow_logs_until_file_appears function and add kubectl_follow_logs

diff --git a/base.yaml b/base.yaml
--- a/base.yaml
+++ b/base.yaml
@@ -102,7 +102,72 @@ functions:
         fi
       fi
     done
-  # Print the logs of a pod, until the specified file appears
+  # Follow pod logs, until the pod finishes
+  # $POD_NAME - name of the pod to print logs for
+  # $CONTAINER - name of the container to print logs for
+  # $TIMEOUT - (optional) (default: 60) timeout in seconds
+  # $REF_COMMAND - (optional) Name of the referring command. This will be printed in the logs.
+  kubectl_follow_logs: |-
+    POD_NAME="$1"
+    CONTAINER="$2"
+    [[ -n $3 ]] && TIMEOUT=$3 || TIMEOUT=60
+    [[ -n $4 ]] && REF_COMMAND="$4" || REF_COMMAND=""
+    [[ -n $REF_COMMAND ]] && THIS_COMMAND_PREFIX="$REF_COMMAND > " || THIS_COMMAND_PREFIX=""
+    THIS_COMMAND="${THIS_COMMAND_PREFIX}kubectl_follow_logs_until_starting"
+    echo ">> $THIS_COMMAND: Running kubectl_follow_logs_until_starting() $@"
+    # Validate pod name
+    require_vars POD_NAME CONTAINER
+    # Follow logs in the background
+    # Start the time
+    START_TIME=$(date +%s)
+    # Wait until the container is created (otherwise logs will not be available)
+    while true; do
+      # If no longer waiting, break
+      if [[ -z "$(kubectl get --namespace=${APP_NAME} pod/$POD_NAME -o jsonpath='{.status.containerStatuses[?(@.name=="'$CONTAINER'")].state.waiting}')" ]]; then
+        echo ">> $THIS_COMMAND: Container $CONTAINER is available.."
+        break
+      else
+        sleep 1
+        kubectl get --namespace=${APP_NAME} pod/$POD_NAME -o jsonpath='{.status.containerStatuses[?(@.name=="'$CONTAINER'")].state.waiting}'
+        now=$(date +%s)
+        if [ $(($now - $START_TIME)) -gt $TIMEOUT ]; then
+          echo ">> $THIS_COMMAND: Error! Timeout waiting for container $CONTAINER to start."
+          exit 1
+        fi
+      fi
+    done
+    # Follow logs
+    echo ">> $THIS_COMMAND: Following logs for pod/$POD_NAME --all-containers=true"
+    kubectl logs --namespace=${APP_NAME} --all-containers=true $POD_NAME --follow &
+    sleep 1
+    # Wait until complete
+    while true; do
+      # If pod disappears, stop
+      if ! kubectl get pod --namespace=${APP_NAME} $POD_NAME --output name > /dev/null 2>&1; then
+        echo ">> $THIS_COMMAND: Pod $POD_NAME no longer exists. Stopping logs."
+        break
+      fi
+      # If the pod is not running, stop
+      POD_STATUS="$(kubectl get --namespace=${APP_NAME} pod/$POD_NAME -o jsonpath='{.status.phase}')"
+      if [[ "$POD_STATUS" != "Running" ]]; then
+        echo ">> $THIS_COMMAND: Pod $POD_NAME is no longer running. Stopping logs."
+        break
+      fi
+      sleep 1
+      now=$(date +%s)
+      if [ $(($now - $START_TIME)) -gt $TIMEOUT ]; then
+        echo ">> $THIS_COMMAND: Error! Timeout waiting for "$FILE_PATH" to appear."
+        exit 1
+      fi
+    done
+    # Kill all background processes showing logs
+    PIDS="$(ps -A -o pid,args | grep " kubectl logs --namespace=${APP_NAME} --all-containers=true $POD_NAME --follow$" | awk '{print $1}' | sort | uniq)"
+    echo ">> $THIS_COMMAND: Killing the log following processes"
+    for PID in $PIDS; do
+      echo ">> $THIS_COMMAND: Killing PID $PID"
+      kill $PID || true
+    done
+  # Follow pod logs, until the specified file appears
   # $FILE_PATH - absolute path of the file to wait for
   # $POD_NAME - name of the pod to print logs for
   # $CONTAINER - name of the container to print logs for
@@ -144,24 +209,29 @@ functions:
     sleep 1
     # Wait for $FILE_PATH to exist
     while true; do
-      # If pod doesnt exist, exit
+      # If pod disappears, exit with error
       if ! kubectl get pod --namespace=${APP_NAME} $POD_NAME --output name > /dev/null 2>&1; then
         echo ">> $THIS_COMMAND: Error! Pod $POD_NAME not found. Exiting."
         exit 1
-      # If the pod is not running, exit
-      elif [[ "$(kubectl get --namespace=${APP_NAME} pod/$POD_NAME -o jsonpath='{.status.phase}')" != "Running" ]]; then
-        echo ">> $THIS_COMMAND: Error! Pod $POD_NAME is not running. Exiting."
+      fi
+      # If the pod stops running, exit with error
+      POD_STATUS="$(kubectl get --namespace=${APP_NAME} pod/$POD_NAME -o jsonpath='{.status.phase}')"
+      if [[ "$POD_STATUS" != "Running" ]]; then
+        echo ">> $THIS_COMMAND: Pod $POD_NAME is no longer running. Exiting."
         exit 1
-      elif kubectl exec --namespace=${APP_NAME} $POD_NAME --container $CONTAINER -- test -f "$FILE_PATH" 2>/dev/null; then
+      fi
+    
+      # If the file appears, break
+      if kubectl exec --namespace=${APP_NAME} $POD_NAME --container $CONTAINER -- test -f "$FILE_PATH" 2>/dev/null; then
         echo ">> $THIS_COMMAND: Found $FILE_PATH. Exiting."
         break
-      else
-        sleep 1
-        now=$(date +%s)
-        if [ $(($now - $START_TIME)) -gt $TIMEOUT ]; then
-          echo ">> $THIS_COMMAND: Error! Timeout waiting for "$FILE_PATH" to appear."
-          exit 1
-        fi
+      fi
+    
+      sleep 1
+      now=$(date +%s)
+      if [ $(($now - $START_TIME)) -gt $TIMEOUT ]; then
+        echo ">> $THIS_COMMAND: Error! Timeout waiting for "$FILE_PATH" to appear."
+        exit 1
       fi
     done
     # Kill all background processes showing logs
