Update image.yaml to allow custom image ref label

diff --git a/v2/image.yaml b/v2/image.yaml
--- a/v2/image.yaml
+++ b/v2/image.yaml
@@ -15,6 +15,10 @@ pipelines:
       - name: dockerfile
         description: Fill path to the Dockerfile, relative to project dir. A .labels file will be created in the same directory as the Dockerfile.
         type: string
+      - name: image-ref-label
+        description: "The name of the image label to use as a version reference point."
+        tyle: string
+        default: "org.opencontainers.image.ref.name"
       - name: log-commit-messages
         description: "Output directory for the git commit logs. If set, creates a file with commit message and all changed assets."
         type: string
@@ -24,6 +28,7 @@ pipelines:
 
       # Get flags
       DOCKERFILE="$(get_flag dockerfile)"
+      IMAGE_REF_LABEL="$(get_flag image-ref-label)"
       LOG_COMMIT_MESSAGES="$(get_flag log-commit-messages)"
 
       # Require vars
@@ -66,13 +71,21 @@ pipelines:
         echo "$LATEST_IMAGE_LABELS"
 
         # Update the .labels file. Get old and new base image references
-        BASE_IMAGE_REF="$(grep -oP 'org.opencontainers.image.ref.name: \K.*' "${LABELS_FILE}" || true)"
+        BASE_IMAGE_REF="$(grep -oP "$IMAGE_REF_LABEL: \K.*" "${LABELS_FILE}" || true)"
         if [ -z "$BASE_IMAGE_REF" ]; then
-          echo "Unable to find 'org.opencontainers.image.ref.name' value in ${LABELS_FILE}"
+          echo "Unable to find $IMAGE_REF_LABEL label and its value in ${LABELS_FILE}"
+          echo "Contents of ${LABELS_FILE}:"
+          cat ${LABELS_FILE}
           echo 1
         fi
         echo "$LATEST_IMAGE_LABELS" > "$LABELS_FILE"
-        NEW_BASE_IMAGE_REF="$(grep -oP 'org.opencontainers.image.ref.name: \K.*' "${LABELS_FILE}")"
+        NEW_BASE_IMAGE_REF="$(grep -oP "${IMAGE_REF_LABEL}: \K.*" "${LABELS_FILE}")"
+        if [ -z "$NEW_BASE_IMAGE_REF" ]; then
+          echo "Unable to find $IMAGE_REF_LABEL label and its value in the new ${LABELS_FILE}"
+          echo "Contents of the new ${LABELS_FILE}:"
+          cat ${LABELS_FILE}
+          echo 1
+        fi
 
         # If LOG_COMMIT_MESSAGES is set, log the changes
         if [ -n "$LOG_COMMIT_MESSAGES" ]; then
