Update image.yaml to provide better error handling

diff --git a/v2/image.yaml b/v2/image.yaml
--- a/v2/image.yaml
+++ b/v2/image.yaml
@@ -66,7 +66,11 @@ pipelines:
         echo "$LATEST_IMAGE_LABELS"
 
         # Update the .labels file. Get old and new base image references
-        BASE_IMAGE_REF="$(grep -oP 'org.opencontainers.image.ref.name: \K.*' "${LABELS_FILE}")"
+        BASE_IMAGE_REF="$(grep -oP 'org.opencontainers.image.ref.name: \K.*' "${LABELS_FILE}" || true)"
+        if [ -z "$BASE_IMAGE_REF" ]; then
+          echo "Unable to find 'org.opencontainers.image.ref.name' value in ${LABELS_FILE}"
+          echo 1
+        fi
         echo "$LATEST_IMAGE_LABELS" > "$LABELS_FILE"
         NEW_BASE_IMAGE_REF="$(grep -oP 'org.opencontainers.image.ref.name: \K.*' "${LABELS_FILE}")"
 
