Allow latest asset for s3-push

diff --git a/v2/s3.yaml b/v2/s3.yaml
--- a/v2/s3.yaml
+++ b/v2/s3.yaml
@@ -37,8 +37,9 @@ pipelines:
         description: "s3/folder"
         type: string
       - name: asset
-        description: "Full path to the file or folder name (must append /), relative to --local-dir; e.g. 2022/05/01/ or myfile.sql.gz"
+        description: "Full path to the file or folder name (must append /), relative to --local-dir; e.g. 2022/05/01/ or myfile.sql.gz or latest (for the latest asset)."
         type: string
+        default: "latest"
       - name: update-marker
         description: "Update .latest marker on --remote-dir. Default: true"
         default: true
@@ -55,6 +56,19 @@ pipelines:
       REMOTE_DIR=$(get_flag remote-dir)
       ASSET=$(get_flag asset)
       UPDATE_MARKER=$(get_flag update-marker)
+      
+      # If latest is set, get the latest asset from $LOCAL_DIR/.latest
+      if [ "$ASSET" == "latest" ]; then
+        if [ ! -f "$LOCAL_DIR/.latest" ]; then
+          echo "Error! $LOCAL_DIR/.latest not found."
+          exit 1
+        fi
+        if [ ! -s "$LOCAL_DIR/.latest" ]; then
+          echo "Error! $LOCAL_DIR/.latest is empty."
+          exit 1
+        fi
+        ASSET=$(cat "$LOCAL_DIR/.latest")
+      fi
 
       # Configure AWS CLI
       export AWS_ACCESS_KEY_ID=$S3_ACCESS_KEY_ID
